drop table Member;
create table Member(
    DB_ID bigint generated by default  as identity,
    id varchar(255),
    pw varchar(255),
    name varchar(255),
    age varchar(255),
    primary key(DB_ID)
);