drop table Member;
drop table beautyShop;
drop table designer;
drop table menu;
drop table order_list;
create table Member(
    DB_ID bigint generated by default  as identity,
    id varchar(255),
    pw varchar(255),
    name varchar(255),
    age varchar(255),
    primary key(DB_ID)
);

create table beautyShop(
    DB_ID bigint generated by default  as identity,
    store_name varchar(255),
    local varchar(255),
    tel_number varchar(255)
);

create table designer(
    id bigint generated by default  as identity,
    name varchar(255),
    specialty varchar(255),
    beautyShopName varchar(255)
);

create table menu(
    DB_ID bigint generated by default  as identity,
    menu_item varchar(255),
    price LONG,
    beautyShopName varchar(255)
);

create table order_list(
    DB_iD bigint generated by default  as identity,
    Shop_id LONG,
    menu_name varchar(255),
    price LONG,
    member_id varchar(255),
    order_date DATETIME,
    cancel boolean,
    reservation_date DATETIME
);

