drop table Member;
create table Member(
    DB_ID bigint generated by default  as identity,
    id varchar(255),
    pw varchar(255),
    name varchar(255),
    age varchar(255),
    primary key(DB_ID)
);

create table beautyShop(
    DB_ID bigint generated by default  as identity,
    store_name varchar(255),
    local varchar(255),
    tel_number varchar(255)
);

create table designer(
    id bigint generated by default  as identity,
    name varchar(255),
    specialty varchar(255),
    beautyShop varchar(255)
);

